apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: isa-cloud-staging
  labels:
    app: minio
    tier: infrastructure
type: Opaque
stringData:
  root-user: minioadmin
  root-password: minioadmin
