apiVersion: v1
kind: Service
metadata:
  name: loki-grpc
  namespace: isa-cloud-staging
  labels:
    app: loki-grpc
    tier: grpc-services
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 50054
    targetPort: 50054
    protocol: TCP
  selector:
    app: loki-grpc
