apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: isa-cloud-staging
  labels:
    app: grafana
    tier: infrastructure
type: Opaque
stringData:
  admin-password: staging_admin_2024
