apiVersion: v1
kind: Service
metadata:
  name: mcp
  namespace: isa-cloud-staging
  labels:
    app: mcp
    tier: applications
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: mcp
