apiVersion: v1
kind: Service
metadata:
  name: model
  namespace: isa-cloud-staging
  labels:
    app: model
    tier: applications
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: model
