apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: isa-cloud-staging
  labels:
    app: user
    tier: applications
spec:
  type: ClusterIP
  ports:
  - name: auth
    port: 8201
    targetPort: 8201
  - name: account
    port: 8202
    targetPort: 8202
  - name: session
    port: 8203
    targetPort: 8203
  - name: authz
    port: 8204
    targetPort: 8204
  - name: audit
    port: 8205
    targetPort: 8205
  - name: notification
    port: 8206
    targetPort: 8206
  - name: payment
    port: 8207
    targetPort: 8207
  - name: wallet
    port: 8208
    targetPort: 8208
  - name: storage
    port: 8209
    targetPort: 8209
  - name: order
    port: 8210
    targetPort: 8210
  - name: task
    port: 8211
    targetPort: 8211
  - name: org
    port: 8212
    targetPort: 8212
  - name: invitation
    port: 8213
    targetPort: 8213
  - name: vault
    port: 8214
    targetPort: 8214
  - name: product
    port: 8215
    targetPort: 8215
  - name: billing
    port: 8216
    targetPort: 8216
  - name: calendar
    port: 8217
    targetPort: 8217
  - name: weather
    port: 8218
    targetPort: 8218
  - name: album
    port: 8219
    targetPort: 8219
  - name: device
    port: 8220
    targetPort: 8220
  - name: ota
    port: 8221
    targetPort: 8221
  - name: media
    port: 8222
    targetPort: 8222
  - name: memory
    port: 8223
    targetPort: 8223
  - name: telemetry
    port: 8225
    targetPort: 8225
  - name: event
    port: 8230
    targetPort: 8230
  selector:
    app: user
