apiVersion: v1
kind: Service
metadata:
  name: mqtt-grpc
  namespace: isa-cloud-staging
  labels:
    app: mqtt-grpc
    tier: grpc-services
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 50053
    targetPort: 50053
    protocol: TCP
  selector:
    app: mqtt-grpc
