apiVersion: v1
kind: Service
metadata:
  name: minio-grpc
  namespace: isa-cloud-staging
  labels:
    app: minio-grpc
    tier: grpc-services
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP
  selector:
    app: minio-grpc
