apiVersion: v1
kind: Service
metadata:
  name: postgres-grpc
  namespace: isa-cloud-staging
  labels:
    app: postgres-grpc
    tier: grpc-services
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 50061
    targetPort: 50061
    protocol: TCP
  selector:
    app: postgres-grpc
