apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: isa-cloud-staging
  labels:
    app: postgres
    tier: infrastructure
type: Opaque
stringData:
  password: staging_postgres_2024
