apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: isa-cloud-staging
  labels:
    app: gateway
    tier: gateway
type: Opaque
stringData:
  database-password: 0npfjCaFaXXnm289
  jwt-secret: staging-secret-key-change-in-production
