apiVersion: v1
kind: Service
metadata:
  name: nats-grpc
  namespace: isa-cloud-staging
  labels:
    app: nats-grpc
    tier: grpc-services
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 50056
    targetPort: 50056
    protocol: TCP
  selector:
    app: nats-grpc
