apiVersion: v1
kind: Service
metadata:
  name: qdrant-grpc
  namespace: isa-cloud-staging
  labels:
    app: qdrant-grpc
    tier: grpc-services
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 50062
    targetPort: 50062
    protocol: TCP
  selector:
    app: qdrant-grpc
